---
- name: subindo container
  hosts: docker
  tasks: 
   - name: criando o green
     docker_container:
      name: green
      image: httpd
      state: started
      volumes:
       - /green:/usr/local/apache2/htdocs/

 name: subindo container
  hosts: docker
  tasks:
   - name: criando o blue
     docker_container:
      name: blue
      image: httpd
      state: started
      volumes:
       - /blue:/usr/local/apache2/htdocs/
